site_name: pgdb | The postgres db handler you have dreamed of :)
repo_url: https://github.com/holdfenytolvaj/pgdb
site_url: http://pgdb.readthedocs.org
theme: readthedocs
pages:
- Home : index.md
- Logger : logger.md
- Connection : connection.md
- Executing SQL files : executingSqlFile.md
- Transaction : transaction.md
- Generate interface for Db : generatingInterfaceForTables.md
- API :
  - PgDb: API/PgDb.md
  - PgSchema: API/PgSchema.md
  - PgTable: API/PgTable.md
  - Condition : API/condition.md
  - Query options : API/QueryOptions.md
